[theme]
base = "dark"
primaryColor = "#0284c7"
backgroundColor = "#0b1120"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
